# FashionM3 Training Configuration
# Fine-tuning Show-O on FashionRec dataset for fashion recommendation

wandb:
  entity: null
  resume: 'auto'

experiment:
  project: "fashionm3"
  name: "fashionvlm-finetuning"
  output_dir: "fashionm3-output"

model:
  vq_model:
    type: "magvitv2"
    vq_model_name: "showlab/magvitv2"
  
  showo:
    load_from_showo: True
    pretrained_model_path: "showlab/show-o-512x512-wo-llava-tuning"
    w_clip_vit: False
    vocab_size: 58498
    llm_vocab_size: 50295
    llm_model_path: 'microsoft/phi-1_5'
    codebook_size: 8192
    num_vq_tokens: 256
    num_new_special_tokens: 10

  gradient_checkpointing: True

dataset:
  type: "fashionrec"
  data_root: "/mnt/c/Users/jonat/desktop/styleai/backend/data"
  und_type: "captioning"
  tasks:
    basic_recommendation:
      weight: 0.26
      data_path: "basic_recommendation"
    personalized_recommendation:
      weight: 0.63
      data_path: "personalized_recommendation"
    alternative_recommendation:
      weight: 0.11
      data_path: "alternative_recommendation"
  params:
    batch_size: 4
    shuffle_buffer_size: 1000
    num_workers: 8
    resolution: 512
    pin_memory: True
    persistent_workers: True
  preprocessing:
    max_seq_length: 381
    resolution: 512
    center_crop: True
    random_flip: False

training:
  enable_multimodal_recommendation: True
  enable_text_to_image: True
  multimodal_recommendation_samples: 40000
  text_to_image_samples: 200000
  gradient_accumulation_steps: 1
  cond_dropout_prob: 0.1
  batch_size: 4
  learning_rate: 1e-4
  weight_decay: 0.01
  warmup_steps: 1000
  max_train_steps: 50000
  mixed_precision: "fp16"
  enable_tf32: True
  save_steps: 1000
  eval_steps: 500
  logging_steps: 100
  mask_ratio_min: 0.5
  mask_ratio_max: 1.0

evaluation:
  metrics:
    - "sentence_bert_similarity"
    - "clip_text_similarity"
    - "clip_image_similarity"
    - "personalization_score"
  eval_batch_size: 2
  num_eval_samples: 1000